export const BIBLE_BOOKS: Record<string, string> = {
  Gen: "Genesis",
  Exod: "Exodus",
  Lev: "Leviticus",
  Num: "Numbers",
  Deut: "Deuteronomy",
  Josh: "Joshua",
  Judg: "Judges",
  Ruth: "Ruth",
  "1Sam": "1 Samuel",
  "2Sam": "2 Samuel",
  "1Kgs": "1 Kings",
  "2Kgs": "2 Kings",
  "1Chr": "1 Chronicles",
  "2Chr": "2 Chronicles",
  Ezra: "Ezra",
  Neh: "Nehemiah",
  Esth: "Esther",
  Job: "Job",
  Ps: "Psalms",
  Prov: "Proverbs",
  Eccl: "Ecclesiastes",
  Song: "Song of Solomon",
  Isa: "Isaiah",
  Jer: "Jeremiah",
  Lam: "Lamentations",
  Ezek: "Ezekiel",
  Dan: "Daniel",
  Hos: "Hosea",
  Joel: "Joel",
  Amos: "Amos",
  Obad: "Obadiah",
  Jonah: "Jonah",
  Mic: "Micah",
  Nah: "Nahum",
  Hab: "Habakkuk",
  Zeph: "Zephaniah",
  Hag: "Haggai",
  Zech: "Zechariah",
  Mal: "Malachi",
  Matt: "Matthew",
  Mark: "Mark",
  Luke: "Luke",
  John: "John",
  Acts: "Acts",
  Rom: "Romans",
  "1Cor": "1 Corinthians",
  "2Cor": "2 Corinthians",
  Gal: "Galatians",
  Eph: "Ephesians",
  Phil: "Philippians",
  Col: "Colossians",
  "1Thess": "1 Thessalonians",
  "2Thess": "2 Thessalonians",
  "1Tim": "1 Timothy",
  "2Tim": "2 Timothy",
  Titus: "Titus",
  Phlm: "Philemon",
  Heb: "Hebrews",
  Jas: "James",
  "1Pet": "1 Peter",
  "2Pet": "2 Peter",
  "1John": "1 John",
  "2John": "2 John",
  "3John": "3 John",
  Jude: "Jude",
  Rev: "Revelation",
};

export const BIBLE_STRUCTURE: Record<string, { chapters: number }> = {
  Genesis: { chapters: 50 },
  Exodus: { chapters: 40 },
  Leviticus: { chapters: 27 },
  Numbers: { chapters: 36 },
  Deuteronomy: { chapters: 34 },
  Joshua: { chapters: 24 },
  Judges: { chapters: 21 },
  Ruth: { chapters: 4 },
  "1 Samuel": { chapters: 31 },
  "2 Samuel": { chapters: 24 },
  "1 Kings": { chapters: 22 },
  "2 Kings": { chapters: 25 },
  "1 Chronicles": { chapters: 29 },
  "2 Chronicles": { chapters: 36 },
  Ezra: { chapters: 10 },
  Nehemiah: { chapters: 13 },
  Esther: { chapters: 10 },
  Job: { chapters: 42 },
  Psalms: { chapters: 150 },
  Proverbs: { chapters: 31 },
  Ecclesiastes: { chapters: 12 },
  "Song of Solomon": { chapters: 8 },
  Isaiah: { chapters: 66 },
  Jeremiah: { chapters: 52 },
  Lamentations: { chapters: 5 },
  Ezekiel: { chapters: 48 },
  Daniel: { chapters: 12 },
  Hosea: { chapters: 14 },
  Joel: { chapters: 3 },
  Amos: { chapters: 9 },
  Obadiah: { chapters: 1 },
  Jonah: { chapters: 4 },
  Micah: { chapters: 7 },
  Nahum: { chapters: 3 },
  Habakkuk: { chapters: 3 },
  Zephaniah: { chapters: 3 },
  Haggai: { chapters: 2 },
  Zechariah: { chapters: 14 },
  Malachi: { chapters: 4 },
  Matthew: { chapters: 28 },
  Mark: { chapters: 16 },
  Luke: { chapters: 24 },
  John: { chapters: 21 },
  Acts: { chapters: 28 },
  Romans: { chapters: 16 },
  "1 Corinthians": { chapters: 16 },
  "2 Corinthians": { chapters: 13 },
  Galatians: { chapters: 6 },
  Ephesians: { chapters: 6 },
  Philippians: { chapters: 4 },
  Colossians: { chapters: 4 },
  "1 Thessalonians": { chapters: 5 },
  "2 Thessalonians": { chapters: 3 },
  "1 Timothy": { chapters: 6 },
  "2 Timothy": { chapters: 4 },
  Titus: { chapters: 3 },
  Philemon: { chapters: 1 },
  Hebrews: { chapters: 13 },
  James: { chapters: 5 },
  "1 Peter": { chapters: 5 },
  "2 Peter": { chapters: 3 },
  "1 John": { chapters: 5 },
  "2 John": { chapters: 1 },
  "3 John": { chapters: 1 },
  Jude: { chapters: 1 },
  Revelation: { chapters: 22 },
};

export const SHORT_TO_OSIS: Record<string, string> = {
  // OT
  gn: "Gen",
  gen: "Gen",
  ex: "Exod",
  exod: "Exod",
  lv: "Lev",
  lev: "Lev",
  nm: "Num",
  num: "Num",
  dt: "Deut",
  deut: "Deut",
  js: "Josh",
  josh: "Josh",
  jg: "Judg",
  judg: "Judg",
  ru: "Ruth",
  ruth: "Ruth",
  "1sa": "1Sam",
  "1sam": "1Sam",
  "2sa": "2Sam",
  "2sam": "2Sam",
  "1ki": "1Kgs",
  "1kings": "1Kgs",
  "2ki": "2Kgs",
  "2kings": "2Kgs",
  "1ch": "1Chr",
  "1chron": "1Chr",
  "2ch": "2Chr",
  "2chron": "2Chr",
  ez: "Ezra",
  ezra: "Ezra",
  ne: "Neh",
  neh: "Neh",
  es: "Esth",
  esth: "Esth",
  jb: "Job",
  job: "Job",
  ps: "Ps",
  psa: "Ps",
  psalm: "Ps",
  psalms: "Ps",
  pr: "Prov",
  prov: "Prov",
  ec: "Eccl",
  eccl: "Eccl",
  so: "Song",
  song: "Song",
  sos: "Song",
  is: "Isa",
  isa: "Isa",
  je: "Jer",
  jer: "Jer",
  la: "Lam",
  lam: "Lam",
  ek: "Ezek",
  ezek: "Ezek",
  da: "Dan",
  dan: "Dan",
  ho: "Hos",
  hos: "Hos",
  jl: "Joel",
  joel: "Joel",
  am: "Amos",
  amos: "Amos",
  ob: "Obad",
  obad: "Obad",
  jn: "John",
  john: "John", // Keep common collision
  jon: "Jonah",
  jonah: "Jonah",
  mi: "Mic",
  mic: "Mic",
  na: "Nah",
  nah: "Nah",
  hb: "Hab",
  hab: "Hab",
  ze: "Zeph",
  zeph: "Zeph",
  hg: "Hag",
  hag: "Hag",
  zc: "Zech",
  zech: "Zech",
  ma: "Mal",
  mal: "Mal",

  // NT
  mt: "Matt",
  matt: "Matt",
  mk: "Mark",
  mark: "Mark",
  lk: "Luke",
  luke: "Luke",
  jo: "John",
  joh: "John",
  ac: "Acts",
  acts: "Acts",
  ro: "Rom",
  rom: "Rom",
  "1co": "1Cor",
  "1cor": "1Cor",
  "2co": "2Cor",
  "2cor": "2Cor",
  ga: "Gal",
  gal: "Gal",
  ep: "Eph",
  eph: "Eph",
  ph: "Phil",
  phil: "Phil",
  philippians: "Phil",
  php: "Phil",
  co: "Col",
  col: "Col",
  "1th": "1Thess",
  "1thess": "1Thess",
  "2th": "2Thess",
  "2thess": "2Thess",
  "1ti": "1Tim",
  "1tim": "1Tim",
  "2ti": "2Tim",
  "2tim": "2Tim",
  ti: "Titus",
  tit: "Titus",
  phm: "Phlm",
  phlm: "Phlm",
  he: "Heb",
  heb: "Heb",
  ja: "Jas",
  jas: "Jas",
  "1pe": "1Pet",
  "1pet": "1Pet",
  "2pe": "2Pet",
  "2pet": "2Pet",
  "1jo": "1John",
  "1jn": "1John",
  "2jo": "2John",
  "2jn": "2John",
  "3jo": "3John",
  "3jn": "3John",
  jd: "Jude",
  jude: "Jude",
  re: "Rev",
  rev: "Rev",
};

// Updated with provided sample XML
export const BIBLE_SAMPLE_XML = `<?xml version="1.0" encoding="UTF-8"?>
<osis xmlns="http://www.bibletechnologies.net/2003/OSIS/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace http://www.bibletechnologies.net/osisCore.2.1.1.xsd">
  <osisText xml:lang="he" osisIDWork="BibleWorksClone" osisRefWork="Bible">
    <header>
      <work osisWork="Strong" xml:lang="en">
         <refSystem>Dict.Strongs</refSystem>
      </work>
    </header>
    
    <div type="book" osisID="Gen">
      <chapter osisID="Gen.1">
        <verse osisID="Gen.1.1">
          <w lemma="b/7225" n="1.0" morph="HR/Ncfsa" id="01xeN">בְּ/רֵאשִׁ֖ית</w>
          <w lemma="1254 a" morph="HVqp3ms" id="01Nvk">בָּרָ֣א</w>
          <w lemma="430" n="1" morph="HNcmpa" id="01TyA">אֱלֹהִ֑ים</w>
          <w lemma="853" morph="HTo" id="01vuQ">אֵ֥ת</w>
          <w lemma="d/8064" n="0.0" morph="HTd/Ncmpa" id="01TSc">הַ/שָּׁמַ֖יִם</w>
          <w lemma="c/853" morph="HC/To" id="01k5P">וְ/אֵ֥ת</w>
          <w lemma="d/776" n="0" morph="HTd/Ncbsa" id="01nPh">הָ/אָֽרֶץ</w>
          <seg type="x-sof-pasuq">׃</seg>
        </verse>
      </chapter>
    </div>

    <div type="book" osisID="John">
      <chapter osisID="John.1">
        <verse osisID="John.1.1">
          <w lemma="1722" morph="PREP" id="n1">Ἐν</w>
          <w lemma="746" morph="N-DSF" id="n2">ἀρχῇ</w>
          <w lemma="1510" morph="V-IAI-3S" id="n3">ἦν</w>
          <w lemma="3588" morph="T-NSM" id="n4">ὁ</w>
          <w lemma="3056" morph="N-NSM" id="n5">λόγος</w>
        </verse>
      </chapter>
    </div>

  </osisText>
</osis>`;
